### ISSUE TITLE
why do you use Redis Pubsub 

### ISSUE THREAD

**Issue by HoangNgo88** [vanyakulinich/latency_node_worker_redis#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by vanyakulinich** [comment]
This latency measurements were a part of larger testings in one of the projects and were moved to a separate repo just in case someone would need similar measurements checks. Consider this a testing tool for cases when latency matters much when you choose for example between http requests and redis messages.
Redis pubsub is used here, because it's used a part of original system design that was tested. In general, redis is a good choice if you need to use event messages not very often or without a high frequency, but if all your infrastructure is event-based  by design (e.g. a batch of microservices), then of course the better choice would be rabbitmq or kafka since they provide better messages management with dead letters queues and dealing with connections interruptions. You can think of redis a light-weight fast simple pubsub and it's a good choice because of easy and fast implementation and integration into any infrastructure, but keep in mind that if the delivery of messages is critical (you can't afford loosing msg) than redis is not what you need - redis doesn't save messages and doesn't guarantee the delivery, as soon as message is sent, you will not be able to restore it in redis, so using redis assumes the connection between components of the system is highly reliable, for example if you you redis cluster in elasticache within aws infrastructure.
Anyway, choosing message broker is always a matter of choice depending on the system you build, and you can always migrate. if you'ra building a prototype of something large, redis might be a good temporary choice for the proto and later you can easy migrate to rabbitmq or kafka if you build proper abstractions in your code
